### ISSUE TITLE
Chinese font

### ISSUE THREAD

**Issue by p2635** [eldstal/cardcinogen#3]
Thank you for creating such a wonderful tool, any tips on how I can use this with Chinese fonts?

I'm on Windows 10.

**Comment by eldstal** [comment]
Thanks for the feedback!

8dd8510 adds unicode (UTF-8) support (note that you must select a unicode font, obviously).

This does not appear to be enough, at least with one of Windows' built-in chinese fonts MingLiu.

Since you have more experience with this, could you please experiment with the new support (see `fluxx/fluxx-utf.json` and `fluxx/cards-utf` for a configuration example) and see what else is needed?

Is there a different text encoding needed for the chinese characters?

**Comment by p2635** [comment]
I haven't been spending much time using the tool lately, closing for now but will come back to it later if needed.

thanks for getting back to me @eldstal
